export const experiences = [
  {
    company: "Sahar SMS",
    role: "Full-Stack Developer",
    period: "07/2024 - 10/2025",
    location: "Tehran",
    bullets: [
      "Built and maintained scalable REST APIs with Express.js and TypeScript — from routing and middleware to JWT auth, RBAC, and rate limiting — focusing on clean, secure, and maintainable code.",
      "Worked closely with PostgreSQL and TypeORM to design efficient data models, manage migrations, handle complex relations, and keep queries fast and reliable.",
      "Improved app speed and stability using Redis for caching, sessions, and throttling; set up background jobs and simple queue systems for async processing.",
      "Developed front-end apps with Next.js and React, using SSR, SSG, and ISR to balance performance and SEO. Leveraged dynamic imports, code splitting, and image optimization for smoother user experiences.",
      "Turned Figma designs into responsive, accessible UIs — making sure forms, loading states, and micro-interactions felt polished and consistent across light and dark themes.",
      "Built a small but powerful design system and shared component library, fully documented in Storybook to help the team move faster and stay consistent.",
      "Added visibility and reliability with Swagger (API docs), Winston (structured logs), Sentry (error monitoring), and basic metrics and tracing to keep an eye on performance.",
    ],
  },
  {
    company: "Apanco",
    role: "Front-End Developer",
    period: "03/2024 - 07/2025",
    location: "Sari, Mazandaran",
    bullets: [
      "Worked closely with design and engineering teams to improve UX flows and deliver measurable, data-driven enhancements — increasing overall user satisfaction by more than 10%.",
      "Turned complex UX/UI wireframes into high-quality, production-ready web applications using React, TypeScript, and Next.js; improved navigation clarity and reduced post-launch issues by 15% through better architecture and component reuse.",
      "Applied advanced Git workflows, including feature branching, peer reviews, and CI/CD pipelines, to maintain clean code, improve collaboration, and streamline release cycles.",
      "Developed and integrated scalable RESTful APIs using Express.js and TypeScript, ensuring clean architecture, strong typing, and efficient data handling across the stack.",
      "Enhanced performance and SEO by optimizing rendering strategies in React and Next.js — implementing dynamic imports, image optimization, and intelligent prefetching for 20% faster page loads.",
      "Integrated secure authentication in Next.js with NextAuth.js, using JWT and refresh tokens to reinforce data security, session stability, and user trust across the platform.",
      "Collaborated with backend engineers to refine API contracts and optimize data flow, ensuring smooth communication between front-end and server components.",
      "Monitored and debugged performance bottlenecks using browser DevTools and Lighthouse audits, leading to consistent performance improvements across major user journeys.",
    ],
  },
  {
    company: "Sepehr Academy",
    role: "Front-End Developer",
    period: "01/2023 - 03/2024",
    location: "Sari, Mazandaran",
    bullets: [
      "Collaborated in a three-member agile team to design and build responsive, high-performance web applications with React — improving workflow efficiency by 25% through better task planning, modular code structure, and reusable component architecture.",
      "Developed visually engaging, pixel-perfect web interfaces using HTML, CSS (Flexbox, Grid), and modern JavaScript (ES6+), focusing on accessibility, performance, and cross-browser compatibility.",
      "Implemented adaptive layouts and accessibility best practices (ARIA roles, keyboard navigation, color contrast) to ensure an inclusive and seamless user experience across all devices.",
      "Transformed wireframes and visual concepts from Figma into functional, production-ready UIs with React and TypeScript, leading to a 20%+ boost in customer satisfaction and user retention.",
      "Built a feature-rich and scalable admin dashboard using React, Context API, and modern UI libraries (MUI/Ant Design), improving data management and reducing manual content updates by over 40%.",
      "Integrated RESTful APIs and handled client-side state management with React Query and Context API, improving data synchronization and reducing load times for dynamic content.",
      "Optimized rendering performance using React hooks, memoization, and lazy loading — resulting in faster load times and smoother UI interactions.",
      "Collaborated with designers and backend developers to refine API contracts, improve data flow, and ensure UI/UX alignment with business goals.",
      "Set up Git-based version control workflows (branching strategy, pull requests, and code reviews) to maintain clean commits and improve collaboration efficiency.",
    ],
  },
];
