export const experiences = [
  {
    company: "Sahar SMS",
    role: "Full-Stack Developer",
    period: "07/2025 - 10/2025",
    location: "Tehran (Remote)",
    bullets: [
      "Built and maintained scalable REST APIs with Express.js and TypeScript, implementing routing, middleware, JWT authentication, RBAC, and rate limiting for secure and efficient operations.",
      "Designed optimized PostgreSQL data models with TypeORM, managing migrations, relations, and high-performance queries; administered databases through pgAdmin.",
      "Improved backend performance using Redis for caching and sessions, and implemented throttling and background jobs for heavy workloads.",
      "Developed full-featured Next.js and React applications leveraging SSR, SSG, ISR, dynamic imports, and code splitting to achieve faster loads and improved SEO.",
      "Translated Figma designs into responsive, accessible UIs with refined forms, polished loading states, and smooth micro-interactions.",
      "Built a reusable design system and component library documented in Storybook, ensuring visual consistency and faster front-end development.",
      "Integrated and tested APIs using Postman, while managing API documentation and debugging workflows.",
      "Enhanced observability with Swagger (API docs), Winston (logging), Sentry (error tracking), and basic metrics/tracing for reliability and performance insights.",
      "Stored and served static assets via AWS S3 buckets, contributing to scalable deployments and optimized cloud storage management.",
    ],
  },
  {
    company: "Hexorix",
    role: "Back-End Developer",
    period: "03/2025 - 06/2025",
    location: "Remote",
    bullets: [
      "Developed scalable and modular backend services using Express.js and NestJS with TypeScript, implementing clean architecture and reusable modules for long-term maintainability.",
      "Designed and optimized relational and non-relational databases using PostgreSQL, MongoDB, TypeORM, and Mongoose — improving query performance and data consistency.",
      "Built secure RESTful APIs and GraphQL endpoints with JWT authentication, role-based access control (RBAC), and request validation for reliable and safe data access.",
      "Integrated caching layers and optimized performance using Redis for sessions, rate limiting, and high-throughput workloads.",
      "Implemented automated testing with Jest, increasing backend reliability and reducing regression bugs across critical endpoints.",
      "Created comprehensive API documentation using Swagger and improved developer experience with clear contracts and testing workflows via Postman.",
      "Developed background workers and cron jobs for heavy tasks such as data processing, queue management, and scheduled operations.",
      "Containerized services with Docker and participated in CI/CD setup to streamline deployments and improve release consistency.",
      "Integrated AWS S3 for secure storage of media and static assets, contributing to scalable cloud-based infrastructure.",
    ],
  },
  {
    company: "Apanco",
    role: "Front-End Developer",
    period: "09/2023 - 03/2025",
    location: "Sari, Mazandaran",
    bullets: [
      "Converted UX/UI wireframes into production-ready React, TypeScript, and Next.js applications, reducing post-launch issues by 15%.",
      "Applied Git workflows and implemented CI/CD pipelines to maintain clean, reliable code and streamline release processes.",
      "Developed and integrated scalable RESTful APIs with Express.js and TypeScript for efficient, maintainable data handling.",
      "Optimized React and Next.js performance through dynamic imports, image optimization, and lazy loading, achieving 20% faster page loads and improved SEO scores.",
      "Implemented secure authentication with NextAuth.js, using JWT and refresh tokens for enhanced user session management.",
      "Collaborated with backend engineers to refine API contracts and optimize data flow, ensuring smooth communication between front-end and back-end services.",
      "Monitored and debugged performance issues using Chrome DevTools and Lighthouse, improving critical user journeys and overall UX.",
    ],
  },
  {
    company: "Sepehr Academy",
    role: "Front-End Developer",
    period: "03/2022 - 09/2023",
    location: "Sari, Mazandaran",
    bullets: [
      "Collaborated within a 3-member Agile team to build scalable, responsive React applications with modular, reusable components — improving development efficiency by 25%.",
      "Delivered pixel-perfect, accessible UIs using HTML, CSS (Flexbox/Grid), and modern JavaScript, ensuring consistent cross-browser performance.",
      "Translated Figma wireframes into production-ready React/TypeScript interfaces, increasing customer satisfaction by 20%+.",
      "Built and maintained a scalable admin dashboard with React, Context API, and modern UI libraries like Material UI, reducing manual updates by 40%.",
      "Integrated and tested RESTful APIs using React Query, Postman, and Axios, improving data synchronization speed and reliability.",
      "Enhanced UI performance with React Hooks, memoization, and lazy loading, achieving smoother and faster user interactions.",
      "Used Git and GitHub for version control, implementing structured branching strategies (feature branches, PR reviews) to streamline collaboration and code quality.",
      "Worked closely with designers and backend developers to refine API contracts and ensure alignment between UI/UX and business goals.",
    ],
  },
];
