export const experiences = [
  {
    company: "Sahar SMS",
    role: "Full-Stack Developer",
    period: "07/2024 - 09/2025",
    location: "Tehran",
    bullets: [
      "Built REST APIs with Express and TypeScript: routing, controllers, middleware, validation, authentication (JWT or OAuth2), RBAC, and rate limiting.",
      "Modeled data and implemented data access with TypeORM: entities, relations, migrations, repositories, transactions; optimized queries and indexes in PostgreSQL or MySQL.",
      "Improved back-end performance with Redis for caching, sessions, and throttling; designed background jobs with simple queues.",
      "Developed front end with Next.js and React: SSR, SSG, ISR, dynamic imports, code splitting, image optimization; data fetching with React Query or Next.js server actions.",
      "Implemented UI and UX best practices: Figma-to-code, consistent form and error patterns, skeleton and loading states, micro-interactions, responsive layouts, dark and light themes, and accessibility (ARIA, keyboard navigation, contrast).",
      "Built a lightweight design system and reusable component library; documented components with Storybook for consistency and speed.",
      "Documented and observed APIs with OpenAPI or Swagger; added structured logging (Winston or Pino), error monitoring (Sentry), and basic metrics and tracing.",
      "Wrote automated tests: Jest and React Testing Library for UI; Supertest for API endpoints; ensured coverage on critical paths and regressions.",
    ],
  },
  {
    company: "Apanco",
    role: "Front-End Developer",
    period: "03/2024 - 07/2025",
    location: "Sari, Mazandaran",
    bullets: [
      "Teamed up with design and development teams to improve UX, and as a result, user satisfaction increased by more than 10%.",
      "Worked closely with UX/UI designers to transform functional wireframes into web applications, which directly contributed to a 15% reduction of post-launch errors in user navigation reported.",
      "Utilized Git and other version control systems to efficiently track project progress, facilitate collaboration, and maintain code integrity.",
      "Built a small-scale real-time app with Socket.IO and Express.js to explore backend event handling and WebSocket integration.",
      "Incorporating better page strategies on web pages using React and Next.js, which led to faster and SEO-friendly web pages, increasing performance and enabling a 20% reduction in load time.",
      "Utilized NextAuth.js in a Next.js project to implement secure authentication with JWT and refresh token support, enhancing session reliability and user data protection.",
    ],
  },
  {
    company: "Sepehr Academy",
    role: "Front-End Developer",
    period: "01/2023 - 03/2024",
    location: "Sari, Mazandaran",
    bullets: [
      "As a team member aspiring to enhance workflow efficiency by 25%, I collaborated in a three-member team developing websites on the React framework.",
      "Engineered visually appealing and fully responsive web pages with HTML, CSS, and JavaScript, aligning with client requirements and boosting user engagement.",
      "Applied responsive and accessible designs to enhance compatibility across a wide range of devices and web browsers, ensuring a seamless user experience.",
      "Designed and refined user interfaces (UI) on Figma, leading to a 20%+ increase in customer satisfaction.",
      "Developed a feature-rich admin panel to enhance UI interactions and streamline management processes, reducing content management time significantly.",
    ],
  },
];
