export const projects = [
    {
        title: "Personal Web Site",
        date: "06/2025",
        link: "https://myself-wheat.vercel.app/",
        github: "https://github.com/KianJanloo/myself",
        type: "React",
    },
    {
        title: "Delta Real Estate Web Site",
        date: "07/2025",
        link: "https://delta-realestate.vercel.app/fa",
        github: "https://github.com/KianJanloo/Delta",
        type: "NextJs",
    },
    {
        title: "Burger Cafe",
        date: "08/2025",
        link: "https://burger-cafee.netlify.app",
        github: "https://github.com/KianJanloo/burger-cafe",
        type: "React",
    },
    {
        title: "Todo List",
        date: "08/2025",
        link: "https://todo-kian.netlify.app/",
        github: "https://github.com/KianJanloo/todo",
        type: "NextJs",
    },
    {
        title: "Time Craft",
        date: "09/2025",
        link: "https://time-craft-kian.netlify.app/",
        github: "https://github.com/KianJanloo/time-craft",
        type: "NextJs",
    },
    {
        title: "Game Store ( Back End )",
        date: "05/2025",
        link: "https://game-store-kappa-woad.vercel.app/",
        github: "https://github.com/KianJanloo/Game-Store",
        type: "Express",
    },
    {
        title: "Book City ( Back End )",
        date: "02/2025",
        link: "https://book-city-production.up.railway.app/",
        github: "https://github.com/KianJanloo/Book-City",
        type: "NestJs",
    },
]