export const projects = [
    {
        title: "redlimit (package)",
        date: "07/2026",
        github: "https://github.com/KianJanloo/redlimit",
        type: "NodeJs",
        company: "Kian Janloo",
    },
    {
        title: "Velonix",
        date: "06/2026",
        link: "https://velonixweb-production.up.railway.app/",
        demoUrl: "https://velonixweb-production.up.railway.app/",
        type: "turbo-repo (NextJs, NestJs)",
        company: "Velonix",
    },
    {
        title: "Rumma Real State",
        date: "10/2025",
        link: "https://rumma-front-end.vercel.app/",
        demoUrl: "https://rumma-front-end.vercel.app/",
        github: "https://github.com/KianJanloo/rumma-front-end",
        type: "NextJs",
        company: "Rumma Real State",
    },
    {
        title: "Delta Real Estate Web Site",
        date: "07/2025",
        link: "https://delta-realestate.vercel.app/fa",
        demoUrl: "https://delta-realestate.vercel.app/fa",
        github: "https://github.com/KianJanloo/Delta",
        type: "NextJs",
        company: "Apanco",
    },
    {
        title: "Call Of Duty",
        date: "11/2025",
        link: "https://call-of-duty-gamma.vercel.app",
        demoUrl: "https://call-of-duty-gamma.vercel.app",
        github: "https://github.com/KianJanloo/call-of-duty",
        type: "TypeScript",
        company: "Sepehr Academy",
    },
    {
        title: "Burger Cafe",
        date: "08/2025",
        link: "https://burger-cafee.netlify.app",
        demoUrl: "https://burger-cafee.netlify.app",
        github: "https://github.com/KianJanloo/burger-cafe",
        type: "React",
        company: "Sepehr Academy",
    },
    {
        title: "Todo List",
        date: "08/2025",
        github: "https://github.com/KianJanloo/todo",
        type: "NextJs",
        company: "Kian Janloo",
    },
    {
        title: "Time Craft",
        date: "09/2025",
        github: "https://github.com/KianJanloo/time-craft",
        type: "NextJs",
        company: "Sahar SMS",
    },
    {
        title: "Game Store ( Back End )",
        date: "05/2025",
        link: "https://game-store-kappa-woad.vercel.app/",
        github: "https://github.com/KianJanloo/Game-Store",
        type: "Express",
        company: "Kian Janloo",
    },
    {
        title: "Book City ( Back End )",
        date: "02/2025",
        github: "https://github.com/KianJanloo/Book-City",
        type: "NestJs",
        company: "Kian Janloo",
    },
    {
        title: "Rumma Real State ( Back End )",
        date: "10/2025",
        link: "https://bama98.liara.run/",
        github: "https://github.com/KianJanloo/rumma-backend",
        type: "NestJs",
        company: "Rumma Real State",
    },
    {
        title: "Bag API ( Back End )",
        date: "11/2025",
        github: "https://github.com/KianJanloo/BagApi",
        type: "ASP.NET",
        company: "Kian Janloo",
    }
]
