export const projects = [
    {
        title: "Lumen",
        image: "/projects/lumen.png",
        date: "08/2026",
        github: "https://github.com/KianJanloo/Lumen",
        link: "https://lumen-web-orcin.vercel.app",
        type: "turbo-repo (NextJs, NestJs)",
        company: "Kian Janloo",
    },
    {
        title: "selfog",
        date: "07/2026",
        github: "https://github.com/KianJanloo/selfog",
        type: "Express, NextJs",
        company: "Kian Janloo",
    },
    {
        title: "redlimit (package)",
        date: "07/2026",
        github: "https://github.com/KianJanloo/redlimit",
        type: "NodeJs",
        company: "Kian Janloo",
    },
    {
        title: "Velonix",
        image: "/projects/velonix.png",
        date: "06/2026",
        link: "https://velonix-alpha.vercel.app/",
        demoUrl: "https://velonix-alpha.vercel.app/",
        type: "turbo-repo (NextJs, NestJs)",
        company: "Velonix",
    },
    {
        title: "Rumma Real State",
        image: "/projects/rumma-real-state.png",
        date: "10/2025",
        link: "https://rumma-front-end.vercel.app/",
        demoUrl: "https://rumma-front-end.vercel.app/",
        github: "https://github.com/KianJanloo/rumma-front-end",
        type: "NextJs, NextJs",
        company: "Rumma Real State",
    },
    {
        title: "Delta Real Estate",
        image: "/projects/delta-real-estate.png",
        date: "07/2025",
        github: "https://github.com/KianJanloo/Delta",
        type: "NextJs",
        company: "Apanco",
    },
    {
        title: "Call Of Duty",
        image: "/projects/call-of-duty.png",
        date: "11/2025",
        link: "https://call-of-duty-gamma.vercel.app",
        demoUrl: "https://call-of-duty-gamma.vercel.app",
        github: "https://github.com/KianJanloo/call-of-duty",
        type: "TypeScript",
        company: "Sepehr Academy",
    },
    {
        title: "Burger Cafe",
        image: "/projects/burger-cafe.png",
        date: "08/2025",
        link: "https://burger-cafee.netlify.app",
        demoUrl: "https://burger-cafee.netlify.app",
        github: "https://github.com/KianJanloo/burger-cafe",
        type: "React",
        company: "Sepehr Academy",
    },
    {
        title: "Todo List",
        image: "/projects/todo-list.png",
        date: "08/2025",
        link: "https://todo-kian.netlify.app/",
        demoUrl: "https://todo-kian.netlify.app/",
        github: "https://github.com/KianJanloo/todo",
        type: "NextJs",
        company: "Kian Janloo",
    },
    {
        title: "Time Craft",
        image: "/projects/time-craft.png",
        date: "09/2025",
        github: "https://github.com/KianJanloo/time-craft",
        link: "https://time-craft-kian.netlify.app/",
        demoUrl: "https://time-craft-kian.netlify.app/",
        type: "NextJs",
        company: "Kian Janloo",
    }
]
