export const skills = [
    { name: 'HTML', rate: 100 },
    { name: 'CSS', rate: 100 },
    { name: 'JavaScript', rate: 100 },
    { name: 'React', rate: 100 },
    { name: 'NextJs', rate: 100 },
    { name: 'Tailwind', rate: 100 },
    { name: 'ShadcnUi', rate: 100 },
    { name: 'Express', rate: 100 },
    { name: 'NestJs', rate: 100 },
    { name: 'Git', rate: 100 },
    { name: 'react-hook-form', rate: 100 },
    { name: 'Formik', rate: 100 },    
    { name: 'Zod', rate: 100 },    
    { name: 'Zustand', rate: 100 },    
    { name: 'react-router', rate: 100 },    
    { name: 'Yup', rate: 100 },    
    { name: 'react-query', rate: 100 },    
    { name: 'axios', rate: 100 },    
    { name: 'NextAuth', rate: 100 },    
    { name: 'JWT', rate: 100 },    
    { name: 'Refresh Token', rate: 100 },    
    { name: 'Postman', rate: 100 },    
    { name: 'Figma', rate: 100 },    
    { name: 'Trello', rate: 100 },    
    { name: 'Jira', rate: 100 },    
    { name: 'SPA', rate: 100 },    
    { name: 'Styled Components', rate: 100 },    
    { name: 'DBeaver', rate: 100 },    
    { name: 'mongoose', rate: 100 },    
    { name: 'typeORM', rate: 100 },    
    { name: 'mongoDB', rate: 100 },    
    { name: 'postgreSQL', rate: 100 },  
    { name: 'Material UI', rate: 100 },  
    { name: 'i18n', rate: 100 },  
    { name: 'WebSocket', rate: 100 },  
]